### ISSUE TITLE
Desired feature: On Results page, permit download of individual output tables

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/archs4#14]
When an ARCHS4 query is performed for a particular gene, and the results page (e.g. https://amp.pharm.mssm.edu/archs4/gene/ACE2) displays numerous tables of output data, it would be helpful to allow users to select each individual table for download as a file; offering multiple formats such as CSV, TSV, and TXT would be convenient.

**Comment by lachmann12** [comment]
Thank you for the comment. We will consider adding this feature when we get the chance.
