### ISSUE TITLE
Newest reference genome version of human_matrix.h5 v8 (Date: 2/2020)

### ISSUE THREAD

**Issue by itszhengan** [MaayanLab/archs4#15]
Hi,

Thank you for your data. Could you please tell me which version of ensembl you use to create human_matrix.h5 v8 (Date: 2/2020)? I need to calculate gene-level TPM from transcript data. Thank you.

Best,
Zheng

**Comment by miltondp** [comment]
Hi @itszhengan. We also want to normalize gene read counts. Apparently they are using hg38: https://github.com/MaayanLab/archs4/blob/master/support/map_genes.r In that file at least they are loading `Homo_sapiens.GRCh38.90.gtf`.

Would you share your code to normalize the data? We are struggling with that too.

**Comment by itszhengan** [comment]
> Hi @itszhengan. We also want to normalize gene read counts. Apparently they are using hg38: https://github.com/MaayanLab/archs4/blob/master/support/map_genes.r In that file at least they are loading `Homo_sapiens.GRCh38.90.gtf`.
> 
> Would you share your code to normalize the data? We are struggling with that too.

Sorry for late reply. But we finally download raw data from ENA and process them by our pipeline, as their data is skeptical for me.
