### ISSUE TITLE
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) :    HDF5. File accessibilty. Unable to open file.

### ISSUE THREAD

**Issue by Waelali-code** [MaayanLab/archs4#18]
I downloaded the R code about human esophagus from https://amp.pharm.mssm.edu/archs4/data.html , and ran on R.

an error was occurred on the step of retrieving information from compressed data,

samples = h5read(destination_file, "meta/Sample_geo_accession")
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) :
HDF5. File accessibilty. Unable to open file.

this problem has been shared here by others, but I could not solve my problem when I applied the suggested solution,  because I am new in using R, please anyone can guide me through this problem, thanks a lot

**Comment by lachmann12** [comment]
It could be due to an incomplete or corrupted file download. What is the md5 checksum of the file you downloaded? It should be:
1335b3c972d7038429aa2d36563f61a2  for human_matrix.h5
28c091161fcaeb844b2143e3bbe42243  for mouse_matrix.h5

**Comment by millerh1** [comment]
I am also having the same issue.

**Comment by lachmann12** [comment]
In case of this error i would recommend a manual download from the archs4 download section. The checksum changed since the last issue. Also the meta data structure has been slightly modified as meta/sample/xxx and meta/gene/xxx
