### ISSUE TITLE
Wrong size of "/meta/samples/singlecellprobability" in mouse matrix v9

### ISSUE THREAD

**Issue by clevermx** [MaayanLab/archs4#20]
In mouse matrix v9 there is only 307268 elements in probabilities vector, but there is 360627 samples in total.
Is it OK? 
Am I right, that I can match these probabilities with first 307268  samples?

**Comment by lachmann12** [comment]
Thank you for bringing it up. I will investigate this right away.

**Comment by lachmann12** [comment]
The predictions have been fixed. The predictions in the human matrix were not affected. The mouse matrix was updated.
https://mssm-seq-matrix.s3.amazonaws.com/mouse_matrix_v9.h5
