### ISSUE TITLE
Difference between human_correlation.rda and human_correlation_archs4.f?

### ISSUE THREAD

**Issue by ShaowenJ** [MaayanLab/archs4#22]
Dear ARCHS4 developers,

As the title, I was wondering what's the difference between these two files? I noticed the value and number of genes are different.
Is the archs4.f more lately??

Thanks!

**Comment by lachmann12** [comment]
The human_correlation_archs4.f file should be the newest file. We will in the future potentially change the normalization method after we do some benchmarks.

**Comment by ShaowenJ** [comment]
Hi @lachmann12 Sorry to reopen this issue again,
But I noticed that both of these 2 files of person correlation values are different from the ARCHS4 gene symbol page, Most similar genes based on co-expression.  Can you tell me a little about the reasons of the difference?
