### ISSUE TITLE
Updating R Scripts with New h5 Matrices

### ISSUE THREAD

**Issue by jasonhan3** [MaayanLab/archs4#23]
When I download an R script to read gene expression data for human data, the initial variables are as follows:

destination_file = "human_matrix_v10.h5"
extracted_expression_file = "GSE30017_expression_matrix.tsv"
url = "https://s3.amazonaws.com/mssm-seq-matrix/human_matrix_v10.h5"

I see that on the [ARCHS4 downloads page ](https://maayanlab.cloud/archs4/download.html) there is a "human_matrix_v11.h5" available. Should the h5 file that the R script prompts the user to download be the updated "v11" data?

**Comment by lachmann12** [comment]
yes, we are working on a better way to access these files. Specifically the archs4py package
