### ISSUE TITLE
Metadata info

### ISSUE THREAD

**Issue by kasumaz** [MaayanLab/archs4#24]
Hi, 
The datasets look very good here. 
I wish to download the files for looking at the human data. I am more interested in the ages of the donors across all of the tissues. Is this metadata embedded within these H5 files? Or could there be a separate metadata file available that contains such information. I would love to be able to get a hold of such information before working on the main files. 
Many thanks.

**Comment by lachmann12** [comment]
Meta data is embedded in the H5 files. As is happens I have a very recent built of a file only containing the meta data for GEO samples. This file contains all samples and some of them are not in the current ARCHS4 release. We hope to have a new release coming soon. https://mssm-data.s3.amazonaws.com/meta.pkl (it is a pickle file which is a dictionary)

**Comment by kasumaz** [comment]
Hi there. This is great. I downloaded it and I started to try and manipulate it locally on python. Do you have any commands I can use to try and view the sample information? I am more interested in ages of donors and tisue/organ info that may be stored there. 
I could not find much when googling on how to get the object structures or head or any other information for pickle files. 
Many thanks.

**Comment by lachmann12** [comment]
The pickle file contains a dictionary. Something like this should work (printing the first GSM meta data):

```
with open('meta.pkl', 'rb') as f:
    meta = pickle.load(f)
   
keys = meta.keys()
print(meta[keys[0]])
```

Not all samples would have age information, and since the meta data is not really standardized very well, it might be anywhere.

**Comment by kasumaz** [comment]
I had to use this line: 

keys = list(meta.keys()) 

in the middle as 

keys = meta.keys()
keys = list(meta.keys())
print(meta[keys[0]]) 

Some info came up. I explore it and see what I can squeeze out of it. Cheers.

**Comment by kasumaz** [comment]
Hi, 
I could convert the file to a .txt file at least to see what the structure of the info looks like. 
I used the following code: 

obj = pickle.load(open("meta.pkl", "rb"))
with open("out.txt", "a") as f:
         pprint.pprint(obj, stream=f)

I am just wondering, is there a way to organise the data better to be able to see something a bit more uniform across the different entries? 
I would mainly like to try to find the type of tissue, age of individual, if it was healthy and human. 
I am not sure if this is possible when looking at the data as it. Maybe you have something that might help. 
Many thanks, 
Kaz
