### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by ebasto** [MaayanLab/archs4#27]
Hello, I had a few questions around the metadata of downloaded h5 files. Namely:

1. the ARCHS4 homepage shows what I assume is the number of FASTQ files that have been processed by the ARCHS4 pipeline, for example human indicates 135 K out of approximately 700 K - the h5 files show approximately 620 K samples. So, am I right assuming that the 135 K has to do with processing? And how do I distinguish the 135 K within the 620 K samples?.
2. Your visualization tool has a break down by tissue and cell type, I can't find the field in the metadata that matches that break down (though I can see that there is a series field that indicates, I assume through some mapping table, which tissue and cell type a sample belongs to.

Those are my main queries for now! 

Thank you in advance,
Edgar

**Comment by yotamroshuji** [comment]
Hi, any chance you got at answer for the second question there?
I wanted to create a tissue-level expression correlation for some genes, but can't find a way to extract the tissue type from the existing h5 metadata..

**Comment by lachmann12** [comment]
ARCHS4 only has the meta data available that is stored in GEO. The tissue information can be extracted using the archs4py package which has decent documentation: https://github.com/MaayanLab/archs4py

Tissue information is most likely found in the meta data fields:
"characteristics_ch1", "source_name_ch1"

Example:

```python
import archs4py as a4

h5_file = "/Users/maayanlab/Downloads/human_gene_v2.2.h5"

# return all meta data for the two fields specified. "" is the filter (in this case all).
meta_1 = a4.meta.meta(h5_file, "", meta_fields=["characteristics_ch1", "source_name_ch1"])

# return all meta data for the two fields specified for samples that match "myoblast" anywhere in meta data
meta_2 = a4.meta.meta(h5_file, "myoblast", meta_fields=["characteristics_ch1", "source_name_ch1"])

# get data right away using meta data search. It will only search in meta_fields=["characteristics_ch1", "extract_protocol_ch1", "source_name_ch1", "title"]
counts = a4.data.meta(h5_file, "myoblast", remove_sc=True)
```

**Comment by yotamroshuji** [comment]
Thanks,
So which meta fields do you use when running the search in the archs4 site? 
I haven't been able to get a match for the number of samples returned by querying "Brain" on the site and using the human_gene_v2.2.h5 file..

**Comment by zouzhaonan** [comment]
The number of samples containing the keyword "N(n)eutrophil" in "characteristics_ch1" **OR** "source_name_ch1" in mouse_gene_v2.5.h5 does not match the sample count displayed on the website.

Is this discrepancy due to a mismatch in dataset versions, or is there an issue with the data extraction procedure?

Specifically, when selecting a tissue on the website, an R script is generated to extract the expression data for the corresponding samples. How are the GSM IDs listed in this script determined?

Are you using some kind of mapping table? Any ideas?
