### ISSUE TITLE
Latest pipeline to create ARCHS4 Version 2.1.2 h5 files?

### ISSUE THREAD

**Issue by seraphzl** [MaayanLab/archs4#28]
Hi,
What is the pipeline used to create human_matrix_v2.1.2.h5 and mouse_matrix_v2.1.2.h5 ? Is it the same as the pipeline mentioned in the 2018 paper?
Thanks.

**Comment by lachmann12** [comment]
The pipeline is rewritten and iptimized, but the basic setup is similar to the one described in the paper.. The main difference is the updated genome annotation. This adds more genes.
