### ISSUE TITLE
Incorrect ensembl id's in v5 mouse gene expression hdf5 file

### ISSUE THREAD

**Issue by lianos** [MaayanLab/archs4#3]
The entries (ordering) of `meta/genes` has changed between the v4 and v5 `mouse_matrix.h5` files, and the corresponding `meta/gene_ensemblid` wasn't updated to match.

For the v5 dataset, it looks like the expression values found in `data/expression` likely correspond to the re-ordered `meta/genes` entries, which makes the v5 `meta/gene_ensemblid` entries wrong ... and likely the other gene-level metadata in the v5 matrix (ie. I just checked that the entrez id's haven't changed from v4, which means they would also be incorrect).

```
library(rhdf5)
library(dplyr)
v4.h5 <- "mouse_matrix_v4.h5"
v5.h5 <- "mouse_matrix_v5.h5"

ginfo <- tibble(
  v4name = h5read(v4.h5, "meta/genes"),
  v4ens = h5read(v4.h5, "meta/gene_ensemblid"),
  v5name = h5read(v5.h5, "meta/genes"),
  v5ens = h5read(v5.h5, "meta/gene_ensemblid"))

head(ginfo)
# A tibble: 6 x 4
#   v4name  v4ens              v5name        v5ens             
#   <chr>   <chr>              <chr>         <chr>             
# 1 A1bg    ENSMUSG00000022347 0610007P14Rik ENSMUSG00000022347
# 2 A1cf    ENSMUSG00000052595 0610009B22Rik ENSMUSG00000052595
# 3 A2m     ENSMUSG00000030111 0610009L18Rik ENSMUSG00000030111
# 4 A3galt2 ENSMUSG00000028794 0610009O20Rik ENSMUSG00000028794
# 5 A4galt  ENSMUSG00000047878 0610010F05Rik ENSMUSG00000047878
# 6 A4gnt   ENSMUSG00000037953 0610010K14Rik ENSMUSG00000037953

all.equal(ginfo$v4ens, ginfo$v5ens)
# [1] TRUE
```

(cc @lachmann12 )

**Comment by lachmann12** [comment]
The gene mapping has been updated. Some gene symbols do not match entries in BioMart. These entries will be NA.

**Comment by lianos** [comment]
Thanks for taking care of this and putting up a new version of the dataset so quickly, @lachmann12 !

Out of curiosity, how is it that some of the genes do not have esnembl identifiers, anyway?

Since you are using kallisto to quantitate against an ensembl based gtf, doesn't every entry/row in that gtf have an ensembl gene identifier? For instance, this may be a different version of the annotations you are using, but:

```
library(rtracklayer)
gtf <- import("Mus_musculus.GRCm38.90.gtf.gz")
sum(is.na(gtf$gene_id))
# [1] 0
table(nchar(gtf$gene_id))
#      18
# 1742489
```

I can understand that if you start from a gene symbols and query for its ensembl id, you can get many misses (NA's), but you've got all the ensembl ids in there right from the get go ... no?

**Comment by lachmann12** [comment]
I used the biomart library in R. I agree that there are transcript IDs from
the beginning. The scripts that build the h5 files have to be refined and
simplified in the next iteration.

library("rhdf5")
library("biomaRt")

ensembl = useMart("ensembl",dataset="mmusculus_gene_ensembl", host="
useast.ensembl.org")
filters = listFilters(ensembl)
attributes = listAttributes(ensembl)

bbm = getBM(attributes =
c('ensembl_gene_id','ensembl_transcript_id','affy_mouse430a_2',
'mgi_symbol', 'entrezgene', 'mgi_id'), mart = ensembl)

genes = h5read("mouse_matrix.h5", "meta/genes")
mm = match(genes, bbm[,4])

length(which(is.na(mm)))
