### ISSUE TITLE
Programmatic way to submit fastq files

### ISSUE THREAD

**Issue by malonzm1** [MaayanLab/archs4#31]
Hi,

I have about 700+ fastq files (16 GSE IDs) I would like to submit to get gene expression files. Is there a way for me to programmatically do this instead of going to the elysium/biojupies webpage and uploading the file each time?

Thanks and good day.

**Comment by lachmann12** [comment]
the ARCHS4py package can run the ARCHS4 pipeline locally and will produce compatible gene count output. This will be faster than uploading that many files.
