### ISSUE TITLE
ENSG genes when using gene_symbols

### ISSUE THREAD

**Issue by malonzm1** [MaayanLab/archs4#34]
Hi,

When I use the R script (h5read(destination_file, "meta/genes/gene_symbol")) the matrix generated includes genes with prefix ENSG along with regular gene symbols. Why is this?

Thanks and good day.

**Comment by lachmann12** [comment]
This is an issue with the ensembl annotation. Some genes do not have an official gene symbol. We use the ensembl id as a placeholder in this case.

**Comment by malonzm1** [comment]
When I run kallisto with the script that generates identical output as elysium/archs4 there are no genes with prefix ENSG (the output with ENSG genes include > 60,000 genes while the output without ENSG genes include > 30,000 genes). Is it possible to make the output from kallisto the same (>60,000 genes)?

**Comment by lachmann12** [comment]
you can use archs4py to mimic the output now
