### ISSUE TITLE
[Question]: License page clarificaion

### ISSUE THREAD

**Issue by tamuanand** [MaayanLab/archs4#35]
Hi @AviMaayan  and @lachmann12 

Thanks for the work here. 

I read through the license page - https://github.com/MaayanLab/archs4/blob/master/LICENSE and I am not clear if say utilities like [gget](https://github.com/pachterlab/gget) can be used programmatically to query the database and if the results of these queries via gget are going to be used in R&D work/presentations in biotech/pharma etc.

As an example: 
- https://github.com/pachterlab/gget#-quick-start-guide has an example for `gget archs4 -w tissue ACE2`

Thanks in advance

**Comment by AviMaayan** [comment]
Dear @tamuanand,

If you are working for a company, the proper thing to do is to contact our MSIP office at msipinfo@mssm.edu.

Best regards,

Avi

**Comment by tamuanand** [comment]
Thanks @AviMaayan 

I have a suggestion:  On your license page, it might be best to also have something like the top portion as seen here: https://github.com/pachterlab/gget/blob/main/LICENSE  - the same shown as a screenshot below

![image](https://github.com/MaayanLab/archs4/assets/8467214/88d3e631-c56c-44db-8a17-9d34e21d8ed6)

Thanks
