### ISSUE TITLE
Fix the footer

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/archs4#37]
Replace BD2K link to ITCR.
Replace DCIC logo with Ma'ayan Lab new logo.
![Screen Shot 2023-09-10 at 2 45 05 PM](https://github.com/MaayanLab/archs4/assets/12749033/7d20e057-4370-4dcb-ab9c-7f2fff919d0b)
![MAAYAN Logo Black_Artwork](https://github.com/MaayanLab/archs4/assets/12749033/5e2fc3a0-87dd-4ef9-adca-403583d01685)

**Comment by lachmann12** [comment]
added changes, running into a build error right now which i need to resolve before pushing.

**Comment by lachmann12** [comment]
deployed
