### ISSUE TITLE
Some questions regarding h5 files

### ISSUE THREAD

**Issue by yotamroshuji** [MaayanLab/archs4#39]
Hey,
I hope this is the right place to ask these questions - please point me in the right direction if not.
There were two questions that arose while working with the downloadable gene expression h5 files:
1) How I can tell if a gene wasn't part of a sample? Currently I assume 0 expression means the gene isn't there. 
2) What is the difference between the "Expression (gene level)" and "Expression (transcript level)" files offered for download on the archs4 site?
3) I was wondering if there is a best practice when creating gene expression correlations using the ARCHS4 data? For example the batch effect correction I saw on the site, or handling missing expressions from samples while measuring expression correlation.

Thank you!

**Comment by lachmann12** [comment]
For ease of use I do recommend using the archs4py library if you are not already doing so.

1. ARCHS4 data is RNA-seq and as such we use the whole genome as potentially profiled. If a gene has 0 counts it means there was no mRNA detected.
2. Gene level expression means that all transcript counts for transcripts belonging to a gene are summed up. Genes have on average 8 transcripts, which contain different exon combinations.
3. There are many ways to normalize gene counts. As a first step I would remove genes that have few counts across the samples. This cut-off will always be somewhat arbitrary. Then apply TMM or quantile normalization. The ARCHS4py package supports normalization. https://github.com/MaayanLab/archs4py

Best,
Alex
