### ISSUE TITLE
What gencode version for 'human_matrix_v1.11.h5' gene name annotation?

### ISSUE THREAD

**Issue by lovenicole** [MaayanLab/archs4#40]
Hello, 

The latest ARCHS4 (ARCHS4 Version 2.3) is based on Ensembl 107. 
Thus, I guessed Entrez gene symbol was annotated based on gencode v41.

However, there is no information for 'human_matrix_v1.11.h5'.
The data was released on 11-16-2021, so I thought the gene symbol was annotated based on gencode v38, which was released on 05-2021. But the 2971 of 35238 genes in 'human_matrix_v1.11.h5' was not overlapped with gencode v38 gene names.

So What gencode version for 'human_matrix_v1.11.h5' gene name annotation?

**Comment by lachmann12** [comment]
All data releases under v1 use the same genome annotation as described in the paper. ARCHS4 uses Ensembl, which is different to gencode. For human data we used the annotation version 87 and for mouse 88. The v2 data uses 107 for both.

Best,
Alex
