### ISSUE TITLE
Gene correlation files on the site 

### ISSUE THREAD

**Issue by yotamgod** [MaayanLab/archs4#42]
Hi,
I noticed that there is new ARCHS4 data (from 2024), yet the gene correlation files are old (2018).
I was wondering if the correlation data on the site itself is up to date and if so, is there a way to download it as a file?
Thanks!

**Comment by lachmann12** [comment]
I added updated matrices to the website. They are in pickle format. I also filter genes with low expression since correlations are not well computed for genes with low expression. I used TMM for normalization.

**Comment by yotamroshuji** [comment]
So the file is gzipped too (requires about 9 GB to read) and can be read using `pd.read_pickle('human_correlation_v2.4.pkl', 'gzip')`.
By the way, the results are different than those on ARCHS4 site (e.g.: The gene GOT1 and GOT2 get different values).
Is this because of the normalization you did?

**Comment by yotamroshuji** [comment]
Another weird issue, is that there are duplicate columns:
![image](https://github.com/MaayanLab/archs4/assets/96071821/e0235525-8a72-4f0b-9049-54eeca50b38e)
Any idea why? Thanks for all the help by the way :)

**Comment by lachmann12** [comment]
The data is aligned at the Ensembl transcript level. These transcripts map to Ensembl genes. The problem is that some Ensembl genes map to the same gene symbol. There is some cases where the transcript sequences of different Ensembl genes is identical. I will have a look whether I can remove duplicates from the matrix somehow, since it is confusing.

**Comment by lachmann12** [comment]
I have rebuilt the files, removed duplicate entries, and omitted the compression. The compression reduced the file size only by 5%.

**Comment by yotamroshuji** [comment]
Great and thanks for the attentive help!
I did notice however that the results are different than those on the ARCHS4 website. 
For example, the result between GOT1 and GOT2 in the dataframe you kindly uploaded:
![image](https://github.com/MaayanLab/archs4/assets/96071821/6166c955-8959-472b-871b-1cbf1fc1da46)

The result on the ARCHS4 website:
![image](https://github.com/MaayanLab/archs4/assets/96071821/9965d39a-f8e7-4795-b706-bb2c3daabd9b)

Any ideas why these are different?
Thanks!
