### ISSUE TITLE
ARCHS4 bugs in the gene pages

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/archs4#5]
The list of co-expressed genes sometimes does not show up. The numbers of the tissues expression levels are not legible (see screenshot that captures both bugs).
![archs4-bugs](https://user-images.githubusercontent.com/12749033/53690637-6c8ca700-3d3c-11e9-8ab3-8ecf572e26cf.png)

**Comment by u8sand** [comment]
This bug came up again in a call -- @lachmann12

**Comment by lachmann12** [comment]
I will look into it.
