### ISSUE TITLE
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) 

### ISSUE THREAD

**Issue by z812206380h** [MaayanLab/archs4#6]
I downloaded the  R code about human esophagus from https://amp.pharm.mssm.edu/archs4/data.html , and ran on R.

an error was occurred on the step of retrieving information from compressed data,

>  samples = h5read(destination_file, "meta/Sample_geo_accession")
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) : 
HDF5. File accessibilty. Unable to open file.

I reinstalled the "rhdf5" package, but the problem was still existing.

**Comment by lachmann12** [comment]
There seems to be an issue with the download function of R which can corrupt the h5 file. Could you try to manually download the h5 file from the download section and skip the download part of the script?

**Comment by z812206380h** [comment]
> There seems to be an issue with the download function of R which can corrupt the h5 file. Could you try to manually download the h5 file from the download section and skip the download part of the script?

Thanks for you help. I manually downloaded the H5 file from official website. But the error still existed. 
Now, I find the error in my code, just because the Chinese character in the setting path. As following: 

setwd("F:/数据分析/GEO/esophageal carcinoma")
> destination_file = "human_matrix.h5"
> checksum = md5sum(destination_file)
> checksum
          human_matrix_download.h5 
"f78da4a1855ff20da768eed1b73508be" 

> samples = h5read(destination_file, "meta/Sample_geo_accession")
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) : 
HDF5. File accessibilty. Unable to open file.

I changed the setting path with English character. No error arose.
> setwd("F:/Data analysis/GEO/esophageal carcinoma")
> destination_file = "human_matrix.h5"
> checksum = md5sum(destination_file)
> checksum
                   human_matrix.h5 
"f78da4a1855ff20da768eed1b73508be" 
> samples = h5read(destination_file, "meta/Sample_geo_accession")
> tissue = h5read(destination_file, "meta/Sample_source_name_ch1")
> genes = h5read(destination_file, "meta/genes")

**Comment by apredeus** [comment]
There seems to be an issue with latest versions of R that prevents the reading of h5 files (at least some - I have found some issues in kallisto repo as well). With R 3.5.1. and the latest rhdf5 package, I get the following error: 

> > samples = h5read(destination_file, "meta/Sample_geo_accession")
> Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
>   HDF5. Dataset. Read failed.

This is true for all .h5 files from ARCHS4 I've tried so far.

**Comment by lianos** [comment]
I'm pretty positive it's not an R thing, but rather a local issue. Likely your download is corrupt? Here are the md5 checksums from the mouse and human v6 matrices, and querying them works fine for me.

```
MD5 (human_matrix_v6.h5) = f78da4a1855ff20da768eed1b73508be
MD5 (mouse_matrix_v6.h5) = 065abb20d2b9d2661e74328de8d23eb3
```

And here's my `sessionInfo()`:

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] rhdf5_2.26.2

loaded via a namespace (and not attached):
[1] compiler_3.5.2 Rhdf5lib_1.4.3
```

**Comment by apredeus** [comment]
Thank you for checking. It must be a bioconda R thing, because md5 sums are OK. 

Downgrading package version to 3.4.1 fixed the problem.

**Comment by lachmann12** [comment]
I have this issue occurring when I try to load multiple large H5 files in R sequentially. I am pretty sure it has to do with the R package. I am glad the downgrading solved the issue.

**Comment by Waelali-code** [comment]
Hi, apredeus , I have the same problem here 

samples = h5read(destination_file, "meta/Sample_geo_accession")
Error in H5Fopen(file, "H5F_ACC_RDONLY", native = native) :
HDF5. File accessibilty. Unable to open file.

as you said downgrading the package help solving this problem, I want to ask which package do you mean, and how to downgrade that package, I am new in using R , so i really need your help 

this is the R version I am using 
R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by lachmann12** [comment]
R has some notorious issue with file downloads on some system configurations. Could you try to download the h5 manually and skip the part in the R script. Then it should work. The file can be found at:

https://amp.pharm.mssm.edu/archs4/download.html

**Comment by sbwiecko** [comment]
Same issue with a folder name containing an accent... often I see R doesn't like the French accent.
