### ISSUE TITLE
Multiple downloads -- hundreds of zipped folders?

### ISSUE THREAD

**Issue by millerh1** [MaayanLab/archs4#8]
Hello!

I noticed today that if you attempt to download multiple files at once, it can spawn over 100 downloads for each one on Chrome. My example is that I tried to download from the mouse+sample page several tissue-specific gene expression files at once (Image attached).
![image](https://user-images.githubusercontent.com/44813811/58353588-76eaa880-7e34-11e9-9699-fbe695729da3.png)

It took a while to start downloading -- and when it did start, it downloaded about 300 zipped folders totaling  nearly 4 GB. I am also fairly sure it downloaded the wrong files since the gene count tsv in the colon folder only had 285 samples -- though according to the page I downloaded it from, it should contain 1169 samples. 

Anyways, hope this is helpful! I really love ARCHS4 and despite this issue I think it's an amazing tool!

Best,
Henry Miller

**Comment by lachmann12** [comment]
Thank you for bringing this up, we will investigate this next week.
